// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/workspaces/CALISTHENICS/node_modules/react');
var { Component } = React;
var ReactNative = require('/workspaces/CALISTHENICS/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('calibuilder', appParameters);
});
require('/workspaces/CALISTHENICS/index.android.js');